### ISSUE TITLE
Foreign Set Names Additionals

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson#285]
See #284 for adding of the 5 core languages.

Languages to Support:
- [x] English [ Added in #284 ]
- [x] French [ Added in #284 ]
- [x] German [ Added in #284 ]
- [x] Italian [ Added in #284 ]
- [x] Spanish [ Added in #284 ]
- [x] Portuguese (Brazil) [ Added in #286 ]
    - https://pt.wikipedia.org/wiki/Expans%C3%B5es_de_Magic:_The_Gathering
- [x] Japanese [ Added in #286 ]
    - http://www.hareruyamtg.com/jp/default.aspx
- [x] Chinese Simplified [ Added in #286 ]
    - http://ig2.cc/sitemap.html
- [x] Korean [ Added in #287 ]
- [ ] Chinese Traditional
- [ ] Russian 
    - http://mtgtrade.net/store/sealed/ (RTR-Present)

___

To support these, I'll need data sources that give me the information for each set in some way. Would rather not have to do this manually and import, but we can if necessary.

To do it manually: Simply add your language key to each value, and translate it! 
Current version: [TranslationTable.json.txt](https://github.com/mtgjson/mtgjson/files/2985935/TranslationTable.json.txt)

**Comment by pvsfair** [comment]
I will help with the Portuguese (Brazil) translations.

**Comment by pvsfair** [comment]
> I will help with the Portuguese (Brazil) translations.

Here are the translations for the Portuguese (Brazil)
[TranslationTable.json.txt](https://github.com/mtgjson/mtgjson/files/2986192/TranslationTable.json.txt)

**Comment by ZeldaZach** [comment]
Appreciated, @pvsfair ! I've automated the Portuguese based on your information :)

**Comment by lfgcampos** [comment]
@ZeldaZach same approach from Korean can be done for Russian: `.../ru/...`

**Comment by ZeldaZach** [comment]
The issue is I don't have a backlog of older russian translations, and I only feel comfortable parsing the newest content. I'll see what I can come up with
